import { NextResponse } from 'next/server';
import { getAdmin } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { makeSlug } from '@/lib/slug';
import { eventSchema } from '@/lib/validations';
import { createAdminClient } from '@/lib/supabase/admin';
function toRow(v:any,userId:string,slug:string){return {slug,title:v.title,description:v.description,cover_image_path:v.coverImagePath??null,host_name:v.hostName,start_at:v.startAt,end_at:v.endAt,timezone:v.timezone,location_type:v.locationType,location_name:v.locationName??null,location_url:v.locationUrl??null,map_url:v.mapUrl??null,registration_enabled:v.registrationEnabled,registration_open_at:v.registrationOpenAt??null,registration_close_at:v.registrationCloseAt??null,capacity:v.capacity??null,approval_mode:v.approvalMode,status:v.status,created_by:userId};}
export async function GET(request:Request){const user=await getAdmin();if(!user)return NextResponse.json({error:{code:'UNAUTHORIZED',message:'로그인이 필요합니다.'}},{status:401});const url=new URL(request.url);const status=url.searchParams.get('status')??'all';const q=url.searchParams.get('q')??'';const supabase=await createClient();let query=supabase.from('events').select('*').order('start_at',{ascending:false});if(status!=='all')query=query.eq('status',status);if(q)query=query.ilike('title',`%${q}%`);const {data,error}=await query;if(error)return NextResponse.json({error:{code:'INTERNAL_ERROR',message:error.message}},{status:500});const admin=createAdminClient();const events=await Promise.all((data??[]).map(async event=>{const {count}=await admin.from('registrations').select('id',{count:'exact',head:true}).eq('event_id',event.id).eq('status','approved');return {...event,approvedCount:count??0};}));return NextResponse.json({events});}
export async function POST(request:Request){const user=await getAdmin();if(!user)return NextResponse.json({error:{code:'UNAUTHORIZED',message:'로그인이 필요합니다.'}},{status:401});const body=await request.json();const parsed=eventSchema.safeParse(body);if(!parsed.success)return NextResponse.json({error:{code:'INVALID_INPUT',message:parsed.error.issues[0]?.message??'입력값을 확인해주세요.'}},{status:400});const supabase=await createClient();let slug=makeSlug();for(let i=0;i<3;i++){const exists=await supabase.from('events').select('id').eq('slug',slug).maybeSingle();if(!exists.data)break;slug=makeSlug();}const {data:event,error}=await supabase.from('events').insert(toRow(parsed.data,user.id,slug)).select().single();if(error||!event)return NextResponse.json({error:{code:'INTERNAL_ERROR',message:error?.message??'생성 실패'}},{status:500});if(parsed.data.fields?.length){await supabase.from('registration_fields').insert(parsed.data.fields.map((field,index)=>({...field,event_id:event.id,sort_order:field.sortOrder??index})));}return NextResponse.json({event:{...event,publicUrl:`${process.env.NEXT_PUBLIC_APP_URL}/${slug}` }},{status:201});}
