'use client';
import { useState } from 'react';
import imageCompression from 'browser-image-compression';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import type { LamaEvent, RegistrationField, FieldType } from '@/lib/types';
import { publicCoverUrl } from '@/lib/formatting';

type ExistingField = RegistrationField & { sort_order?: number; sortOrder?: number };
type DraftField = { type: FieldType; label: string; description: string; placeholder: string; required: boolean; optionsText: string };
function initialField(field: ExistingField, index: number): DraftField { return { type: field.type, label: field.label, description: field.description ?? '', placeholder: field.placeholder ?? '', required: field.required, optionsText: (field.options ?? []).map(option => `${option.label}:${option.value}`).join(', ') || '' }; }

export default function EventForm({event,fields}:{event?:LamaEvent;fields?:ExistingField[]}) {
  const router = useRouter();
  const [title,setTitle]=useState(event?.title??''); const [description,setDescription]=useState(event?.description??''); const [hostName,setHostName]=useState(event?.host_name??'');
  const [startAt,setStartAt]=useState(event?.start_at?.slice(0,16)??''); const [endAt,setEndAt]=useState(event?.end_at?.slice(0,16)??''); const [registrationOpenAt,setRegistrationOpenAt]=useState(event?.registration_open_at?.slice(0,16)??''); const [registrationCloseAt,setRegistrationCloseAt]=useState(event?.registration_close_at?.slice(0,16)??''); const [locationType,setLocationType]=useState<'in_person'|'online'>(event?.location_type??'in_person');
  const [locationName,setLocationName]=useState(event?.location_name??''); const [locationUrl,setLocationUrl]=useState(event?.location_url??''); const [capacity,setCapacity]=useState(event?.capacity?.toString()??''); const [approvalMode,setApprovalMode]=useState<'auto'|'manual'>(event?.approval_mode??'auto');
  const [status,setStatus]=useState<'draft'|'published'|'cancelled'>(event?.status??'published'); const [registrationEnabled,setRegistrationEnabled]=useState(event?.registration_enabled??true); const [coverPath,setCoverPath]=useState(event?.cover_image_path??'');
  const [coverFile,setCoverFile]=useState<File|null>(null); const [fieldsDraft,setFieldsDraft]=useState<DraftField[]>((fields??[]).map(initialField)); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const updateField=(index:number,patch:Partial<DraftField>)=>setFieldsDraft(current=>current.map((field,i)=>i===index?{...field,...patch}:field));
  const save=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const fields=fieldsDraft.map((field,index)=>({type:field.type,label:field.label,description:field.description||null,placeholder:field.placeholder||null,options:field.type==='select'?field.optionsText.split(',').map(item=>item.trim()).filter(Boolean).map(item=>{const [label,value]=item.split(':');return {label:label.trim(),value:(value??label).trim()};}):null,required:field.required,sortOrder:index}));const payload={title,description,hostName,startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString(),timezone:'Asia/Seoul',locationType,locationName:locationType==='in_person'?locationName:null,locationUrl:locationType==='online'?locationUrl:null,mapUrl:null,registrationEnabled,registrationOpenAt:registrationOpenAt?new Date(registrationOpenAt).toISOString():null,registrationCloseAt:registrationCloseAt?new Date(registrationCloseAt).toISOString():null,capacity:capacity?Number(capacity):null,approvalMode,status,coverImagePath:coverPath||null,fields};const res=await fetch(event?`/api/admin/events/${event.id}`:'/api/admin/events',{method:event?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok)throw new Error(json.error?.message??'저장에 실패했습니다.');const id=json.event.id;if(coverFile){const compressed=await imageCompression(coverFile,{maxSizeMB:2,maxWidthOrHeight:1600,useWebWorker:true,fileType:'image/webp'});const form=new FormData();form.append('file',compressed,'cover.webp');form.append('eventId',id);const upload=await fetch('/api/admin/upload',{method:'POST',body:form});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error?.message??'이미지 업로드에 실패했습니다.');await fetch(`/api/admin/events/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({coverImagePath:uploaded.path})});}router.push(`/admin/events/${id}`);}catch(err){setError(err instanceof Error?err.message:'저장에 실패했습니다.');}finally{setLoading(false);}};
  return <form onSubmit={save} className="admin-form">
    <div className="field"><label>대표 이미지</label>{coverPath&&<Image src={publicCoverUrl(coverPath)??''} alt="현재 대표 이미지" width={180} height={180} style={{width:180,height:180,objectFit:'cover',borderRadius:12}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0]??null;if(file&&file.size>10*1024*1024){setError('입력 이미지는 10MB 이하여야 합니다.');return;}setCoverFile(file);}}/></div>
    <div className="field"><label>이벤트 제목 *</label><input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></div>
    <div className="field"><label>호스트명 *</label><input required value={hostName} onChange={e=>setHostName(e.target.value)}/></div>
    <div className="field"><label>이벤트 설명 (마크다운) *</label><textarea required value={description} onChange={e=>setDescription(e.target.value)}/></div>
    <div className="admin-form-grid"><div className="field"><label>시작 *</label><input required type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)}/></div><div className="field"><label>종료 *</label><input required type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></div></div>
    <div className="field"><label>장소 유형</label><select value={locationType} onChange={e=>setLocationType(e.target.value as 'in_person'|'online')}><option value="in_person">오프라인</option><option value="online">온라인</option></select></div>
    {locationType==='in_person'?<div className="field"><label>장소 *</label><input required value={locationName} onChange={e=>setLocationName(e.target.value)}/></div>:<div className="field"><label>온라인 링크 *</label><input required type="url" value={locationUrl} onChange={e=>setLocationUrl(e.target.value)}/></div>}
    <div className="admin-form-grid"><div className="field"><label>정원</label><input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)} placeholder="무제한"/></div><div className="field"><label>승인 방식</label><select value={approvalMode} onChange={e=>setApprovalMode(e.target.value as 'auto'|'manual')}><option value="auto">자동 승인</option><option value="manual">수동 승인</option></select></div></div>
    <label><input type="checkbox" checked={registrationEnabled} onChange={e=>setRegistrationEnabled(e.target.checked)}/> 참가 신청 받기</label>
    <div className="admin-form-grid"><div className="field"><label>신청 시작</label><input type="datetime-local" value={registrationOpenAt} onChange={e=>setRegistrationOpenAt(e.target.value)}/></div><div className="field"><label>신청 마감</label><input type="datetime-local" value={registrationCloseAt} onChange={e=>setRegistrationCloseAt(e.target.value)}/></div></div>
    <div className="field"><label>공개 상태</label><select value={status} onChange={e=>setStatus(e.target.value as 'draft'|'published'|'cancelled')}><option value="draft">비공개 초안</option><option value="published">공개</option><option value="cancelled">취소</option></select></div>
    <section className="admin-form-section"><div className="admin-form-section-header"><h2>신청 질문</h2><button type="button" className="button secondary" onClick={()=>setFieldsDraft([...fieldsDraft,{type:'text',label:'',description:'',placeholder:'',required:false,optionsText:''}])}>질문 추가</button></div>{fieldsDraft.map((field,index)=><div key={index} className="admin-question"><div className="admin-form-section-header"><strong>질문 {index+1}</strong><button type="button" className="button secondary" onClick={()=>setFieldsDraft(fieldsDraft.filter((_,i)=>i!==index))}>삭제</button></div><div className="admin-form-grid"><div className="field"><label>유형</label><select value={field.type} onChange={e=>updateField(index,{type:e.target.value as FieldType})}><option value="text">짧은 답변</option><option value="textarea">긴 답변</option><option value="select">선택</option><option value="checkbox">체크박스</option></select></div><div className="field"><label>질문</label><input required value={field.label} onChange={e=>updateField(index,{label:e.target.value})}/></div></div>{field.type==='select'&&<div className="field"><label>선택지</label><input required value={field.optionsText} placeholder="개발자:developer, 기획자:planner" onChange={e=>updateField(index,{optionsText:e.target.value})}/></div>}<label><input type="checkbox" checked={field.required} onChange={e=>updateField(index,{required:e.target.checked})}/> 필수 질문</label></div>)}</section>
    {error&&<p className="error">{error}</p>}<button className="button" disabled={loading}>{loading?'저장 중...':'저장'}</button>
  </form>;
}
