import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import ReactMarkdown from 'react-markdown';
import rehypeSanitize from 'rehype-sanitize';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { registrationState } from '@/lib/registration';
import { formatEventDate, appUrl, publicCoverUrl } from '@/lib/formatting';
import type { LamaEvent, RegistrationField } from '@/lib/types';
import RegistrationForm from '@/components/RegistrationForm';

async function getEvent(slug:string) { const supabase=await createClient(); const {data:event}=await supabase.from('events').select('*').eq('slug',slug).maybeSingle(); if(!event)return null; const {data:fields}=await supabase.from('registration_fields').select('*').eq('event_id',event.id).order('sort_order'); const admin=createAdminClient(); const {count}=await admin.from('registrations').select('id',{count:'exact',head:true}).eq('event_id',event.id).eq('status','approved'); return {event:event as LamaEvent,fields:(fields??[]) as RegistrationField[],approvedCount:count??0}; }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const data=await getEvent(slug);if(!data)return {title:'이벤트를 찾을 수 없습니다.'};const image=publicCoverUrl(data.event.cover_image_path);return {title:data.event.title,description:data.event.description.slice(0,160),robots:{index:false,follow:false},alternates:{canonical:appUrl(`/${slug}`)},openGraph:{title:data.event.title,description:data.event.description.slice(0,160),url:appUrl(`/${slug}`),type:'website',images:image?[{url:image}]:undefined}};}
export default async function EventPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const data=await getEvent(slug);if(!data||data.event.status==='draft')notFound();const state=registrationState(data.event,data.approvedCount);const disabled=state!=='open';const labels={not_open:'신청 시작 전',open:'신청 가능',closed:'신청 마감',full:'정원 마감',cancelled:'취소된 이벤트'};const cover=publicCoverUrl(data.event.cover_image_path);return <main className="container" style={{padding:'48px 0 80px'}}><Link href="/" className="muted">← Inha의 이벤트</Link><div style={{display:'grid',gridTemplateColumns:'minmax(280px,420px) 1fr',gap:64,marginTop:28}}><aside><div className="card" style={{overflow:'hidden'}}>{cover?<Image src={cover} alt="" width={840} height={840} priority style={{width:'100%',height:'auto',aspectRatio:'1',objectFit:'cover'}}/>:<div style={{aspectRatio:'1',display:'grid',placeItems:'center',background:'#f1f1f1',fontSize:72,color:'#777'}}>I</div>}<div style={{padding:22}}><p className="muted">{data.event.host_name}</p><strong>{data.approvedCount}명 참가</strong></div></div></aside><article style={{maxWidth:720}}><span className="pill">{labels[state]}</span><h1 style={{fontSize:'clamp(34px,5vw,60px)',lineHeight:1.08,margin:'18px 0'}}>{data.event.title}</h1><p className="muted" style={{lineHeight:1.7}}>{formatEventDate(data.event.start_at,data.event.end_at,data.event.timezone)}<br/>{data.event.location_type==='online'?<a href={data.event.location_url!} target="_blank" rel="noreferrer">온라인 링크 열기</a>:data.event.map_url?<a href={data.event.map_url} target="_blank" rel="noreferrer">{data.event.location_name} 지도 보기</a>:data.event.location_name}</p><section className="card" style={{padding:24,margin:'30px 0'}}><h2 style={{marginTop:0}}>참가 신청</h2>{disabled?<p className="muted">{labels[state]} 상태입니다.</p>:<RegistrationForm eventId={data.event.id} fields={data.fields}/>}</section><section><h2>이벤트 소개</h2><div style={{lineHeight:1.8}}><ReactMarkdown rehypePlugins={[rehypeSanitize]}>{data.event.description}</ReactMarkdown></div></section></article></div></main>}
