import { NextResponse } from 'next/server';
import { registerSchema } from '@/lib/validations';
import { createAdminClient } from '@/lib/supabase/admin';
import { newCancelToken, tokenHash } from '@/lib/registration';
import { sendRegistrationEmail, statusEmailType } from '@/lib/email';
import type { LamaEvent, Registration } from '@/lib/types';

export const runtime = 'nodejs';
const messages:Record<string,string>={CONSENT_REQUIRED:'개인정보 수집·이용에 동의해주세요.',EVENT_NOT_FOUND:'이벤트를 찾을 수 없습니다.',REGISTRATION_NOT_OPEN:'참가 신청 기간이 아닙니다.',DUPLICATE_EMAIL:'이미 신청한 이메일입니다.',EVENT_FULL:'이 이벤트는 정원이 마감되었습니다.'};
export async function POST(request:Request){try{const parsed=registerSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:{code:'INVALID_INPUT',message:'입력값을 확인해주세요.'}},{status:400});const input=parsed.data;if(input.website)return NextResponse.json({registrationId:'honeypot',status:'approved',emailStatus:'sent'},{status:201});const admin=createAdminClient();const cancelToken=newCancelToken();const {data:rpc,error}=await admin.rpc('register_for_event',{p_event_id:input.eventId,p_name:input.name,p_email:input.email,p_answers:input.answers,p_consent:input.consent,p_cancel_token_hash:tokenHash(cancelToken)});if(error){const message=messages[error.message]??'신청을 처리할 수 없습니다.';return NextResponse.json({error:{code:error.message,message}},{status:message==='신청을 처리할 수 없습니다.'?500:400});}const result=typeof rpc==='string'?JSON.parse(rpc):rpc as {id:string;status:string};const [{data:event},{data:registration}]=await Promise.all([admin.from('events').select('*').eq('id',input.eventId).single(),admin.from('registrations').select('*').eq('id',result.id).single()]);let emailStatus:'sent'|'failed'='sent';let errorMessage:string|undefined;try{const type=statusEmailType(result.status as Registration['status']);await sendRegistrationEmail(type,event as LamaEvent,{name:input.name,email:input.email,cancelToken});}catch(error){emailStatus='failed';errorMessage=error instanceof Error?error.message:'이메일 발송 실패';}await admin.from('email_deliveries').insert({registration_id:result.id,email_type:statusEmailType(result.status as Registration['status']),attempt_no:1,to_email:input.email,status:emailStatus,sent_at:emailStatus==='sent'?new Date().toISOString():null,error_message:errorMessage??null});return NextResponse.json({registrationId:result.id,status:result.status,emailStatus},{status:201});}catch(error){return NextResponse.json({error:{code:'INTERNAL_ERROR',message:error instanceof Error?error.message:'서버 오류가 발생했습니다.'}},{status:500});}}
